/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import irs.Searcher;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.core.WhitespaceAnalyzer;
import org.apache.lucene.analysis.en.EnglishAnalyzer;
import org.apache.lucene.analysis.miscellaneous.PerFieldAnalyzerWrapper;

import org.apache.lucene.analysis.miscellaneous.PerFieldAnalyzerWrapper;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.search.similarities.ClassicSimilarity;
import org.apache.lucene.search.similarities.Similarity;

/**
 *
 * @author David
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Searcher searcher = new Searcher();
    //Analyzer analyzer = new EnglishAnalyzer();
    Map<String, Analyzer> analyzerPerField;
    Similarity similarity = new ClassicSimilarity();
    ButtonGroup booleanButtons;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.analyzerPerField = new HashMap<String, Analyzer>();
        analyzerPerField.put("id", new WhitespaceAnalyzer());
        analyzerPerField.put("owneruserid", new WhitespaceAnalyzer());
        analyzerPerField.put("parentid", new WhitespaceAnalyzer());
        analyzerPerField.put("date", new WhitespaceAnalyzer());
        analyzerPerField.put("score", new WhitespaceAnalyzer());
        analyzerPerField.put("isacceptedanswer", new WhitespaceAnalyzer());
        analyzerPerField.put("tags", new WhitespaceAnalyzer());
        analyzerPerField.put("body", new EnglishAnalyzer());
        analyzerPerField.put("code", new WhitespaceAnalyzer());
        initComponents();
        buttonGroup2.add(ANDButton);
        buttonGroup2.add(ORButton);
        buttonGroup2.add(NOTButton);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        BotonSalir = new javax.swing.JButton();
        LabelBuscar = new javax.swing.JLabel();
        TextFieldBuscar = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaResultado = new javax.swing.JTextArea();
        DocumentosEncontradosLabel = new javax.swing.JLabel();
        TextFieldDocumentosEncontrados = new javax.swing.JTextField();
        ComboBox1 = new javax.swing.JComboBox<>();
        LabelBuscar2 = new javax.swing.JLabel();
        ComboBox2 = new javax.swing.JComboBox<>();
        TextFieldBuscar2 = new javax.swing.JTextField();
        ANDButton = new javax.swing.JRadioButton();
        ORButton = new javax.swing.JRadioButton();
        NOTButton = new javax.swing.JRadioButton();
        nDocsLabel = new javax.swing.JLabel();
        nDocsMostradosTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        LabelBuscar.setText("Buscar:");

        TextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBuscarActionPerformed(evt);
            }
        });

        BotonBuscar.setText("Busca");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        TextAreaResultado.setColumns(20);
        TextAreaResultado.setRows(5);
        jScrollPane2.setViewportView(TextAreaResultado);

        DocumentosEncontradosLabel.setText("Documentos encontrados:");

        TextFieldDocumentosEncontrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDocumentosEncontradosActionPerformed(evt);
            }
        });

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "owneruserid", "date", "parentid", "score", "isacceptedanswer", "body", "code", "tags" }));
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });

        LabelBuscar2.setText("Buscar:");

        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "owneruserid", "date", "parentid", "score", "isacceptedanswer", "body", "code", "tags" }));
        ComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox2ActionPerformed(evt);
            }
        });

        TextFieldBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBuscar2ActionPerformed(evt);
            }
        });

        ANDButton.setText("AND");
        ANDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANDButtonActionPerformed(evt);
            }
        });

        ORButton.setText("OR");
        ORButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORButtonActionPerformed(evt);
            }
        });

        NOTButton.setText("NOT");
        NOTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTButtonActionPerformed(evt);
            }
        });

        nDocsLabel.setText("Numero de documentos mostrados:");

        nDocsMostradosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nDocsMostradosTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nDocsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nDocsMostradosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(DocumentosEncontradosLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextFieldDocumentosEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelBuscar2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextFieldBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelBuscar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(ANDButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ORButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NOTButton)))
                                .addGap(61, 61, 61)
                                .addComponent(BotonBuscar)
                                .addGap(0, 90, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(BotonSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelBuscar)
                            .addComponent(TextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelBuscar2)
                            .addComponent(TextFieldBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANDButton)
                            .addComponent(ORButton)
                            .addComponent(NOTButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(BotonBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nDocsLabel)
                    .addComponent(nDocsMostradosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocumentosEncontradosLabel)
                    .addComponent(TextFieldDocumentosEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBuscarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        try {
            String campo = ComboBox1.getSelectedItem().toString();
            String campo2 = ComboBox2.getSelectedItem().toString();
            
            String boolOperation = "";
            if(ANDButton.isSelected())
                boolOperation += "AND";
            if(ORButton.isSelected())
                boolOperation += "OR";
            if(NOTButton.isSelected())
                boolOperation += "NOT";
            
            TextAreaResultado.setText(searcher.indexSearch(analyzerPerField, similarity, TextFieldBuscar.getText(), campo, TextFieldBuscar2.getText(), campo2, boolOperation, nDocsMostradosTextField.getText()));
            TextFieldDocumentosEncontrados.setText(searcher.getDocEncontrados());
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void TextFieldDocumentosEncontradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDocumentosEncontradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDocumentosEncontradosActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void ComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox2ActionPerformed

    private void TextFieldBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBuscar2ActionPerformed

    private void ANDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANDButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANDButtonActionPerformed

    private void ORButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ORButtonActionPerformed

    private void NOTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOTButtonActionPerformed

    private void nDocsMostradosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nDocsMostradosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nDocsMostradosTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ANDButton;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JLabel DocumentosEncontradosLabel;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelBuscar2;
    private javax.swing.JRadioButton NOTButton;
    private javax.swing.JRadioButton ORButton;
    private javax.swing.JTextArea TextAreaResultado;
    private javax.swing.JTextField TextFieldBuscar;
    private javax.swing.JTextField TextFieldBuscar2;
    private javax.swing.JTextField TextFieldDocumentosEncontrados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nDocsLabel;
    private javax.swing.JTextField nDocsMostradosTextField;
    // End of variables declaration//GEN-END:variables
}
